name: Update Pinned Repos and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch pinned repos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -X POST -d '{
            "query": "{ user(login: \"dcosodev\") { pinnedItems(first: 6, types: REPOSITORY) { edges { node { ... on Repository { name description url openGraphImageUrl } } } } } }"
          }' https://api.github.com/graphql)
          
          if echo "$response" | jq -e '.data.user.pinnedItems.edges' > /dev/null; then
            echo "$response" | jq '.data.user.pinnedItems.edges[].node' > pinned-repos.json
            echo "Pinned repos fetched successfully"
          else
            echo "Error fetching pinned repos. Creating empty array."
            echo "[]" > pinned-repos.json
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
